### ISSUE TITLE
probable faulty data augmentation - numpy seed initialization

### ISSUE THREAD

**Issue by e-maud** [dhlab-epfl/dhSegment-torch#4]
The random seed initialisation using numpy might be faulty:

https://www.reddit.com/r/MachineLearning/comments/mocpgj/p_using_pytorch_numpy_a_bug_that_plagues/ 

Many thanks for checking and, ideally, correcting. Happy to help if needed.

**Comment by RPetitpierre** [comment]
Hello Maud,

Merci pour l’info ! Je vais essayer de résoudre le bug. Cependant, le driver NVIDIA semble avoir un problème, en tout cas sur ma session du cluster36. As-tu aussi cette erreur ? Si non, sais-tu à quoi ça pourrait correspondre ?


(dhs) ***@***.***:/scratch/students/remi$ nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



Merci et bonne fin de journée !





Rémi

From: Maud Ehrmann ***@***.***>
Reply to: dhlab-epfl/dhSegment-torch ***@***.***>
Date: Monday 12 April 2021 at 10:07
To: dhlab-epfl/dhSegment-torch ***@***.***>
Cc: Petitpierre Rémi Guillaume ***@***.***>, Assign ***@***.***>
Subject: [dhlab-epfl/dhSegment-torch] probable faulty data augmentation - numpy seed initialization (#4)


The random seed initialisation using numpy might be faulty:

https://www.reddit.com/r/MachineLearning/comments/mocpgj/p_using_pytorch_numpy_a_bug_that_plagues/

Many thanks for checking and, ideally, correcting. Happy to help if needed.

**Comment by RPetitpierre** [comment]
Corrective pull request #5
